package com.aluno.arthur.lista1;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.Toast;

import java.util.ArrayList;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        final ListView lista = (ListView) findViewById(R.id.lstEquipes);
        final ArrayList<String> equipes = preencheDados();
        ArrayAdapter<String> adaptador = new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,equipes);
        lista.setAdapter(adaptador);

        lista.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                Log.i("TAG", "usuário clicou no item:" + lista.getItemAtPosition(position).toString());
                Toast.makeText(getApplicationContext(), "Você clicou em: " + equipes.get(position), Toast.LENGTH_LONG).show();
                goToMainAvtivity3(equipes.get(position));

            }
        });
    }

    public void goToMainAvtivity3(String item) {
        Intent i = new Intent(this, Main2Activity.class);
        i.putExtra("POKEMON", item);
        startActivity(i);
    }

    ArrayList<String> preencheDados() {
        ArrayList<String> arrayList = new ArrayList<>();
        arrayList.add("Bulbasaur");
        arrayList.add("Ivysaur");
        arrayList.add("Venusaur");
        arrayList.add("Charmander");
        arrayList.add("Charmeleon");
        arrayList.add("Charizard");
        arrayList.add("Squirtle");
        arrayList.add("Wartortle");
        arrayList.add("Blastoise");
        arrayList.add("Caterpie");
        arrayList.add("Metapod");
        arrayList.add("Butterfree");
        arrayList.add("Weedle");
        arrayList.add("Kakuna");
        arrayList.add("Beedrill");
        arrayList.add("Pidgey");
        arrayList.add("Pidgeotto");
        arrayList.add("Pidgeot");
        arrayList.add("Rattata");
        arrayList.add("Raticate");
        arrayList.add("Spearow");
        arrayList.add("Fearow");
        arrayList.add("Ekans");
        arrayList.add("Arbok");
        arrayList.add("Pikachu");
        arrayList.add("Raichu");
        arrayList.add("Sandshrew");
        arrayList.add("Sandslash");
        arrayList.add("Nidoran♀");
        arrayList.add("Nidorina");
        arrayList.add("Nidoqueen");
        arrayList.add("Nidoran♂");
        arrayList.add("Nidorino");
        arrayList.add("Nidoking");
        arrayList.add("Clefairy");
        arrayList.add("Clefable");
        arrayList.add("Vulpix");
        arrayList.add("Ninetales");
        arrayList.add("Jigglypuff");
        arrayList.add("Wigglytuff");
        arrayList.add("Zubat");
        arrayList.add("Golbat");
        arrayList.add("Oddish");
        arrayList.add("Gloom");
        arrayList.add("Vileplume");
        arrayList.add("Paras");
        arrayList.add("Parasect");
        arrayList.add("Venonat");
        arrayList.add("Venomoth");
        arrayList.add("Diglett");
        arrayList.add("Dugtrio");
        arrayList.add("Meowth");
        arrayList.add("Persian");
        arrayList.add("Psyduck");
        arrayList.add("Golduck");
        arrayList.add("Mankey");
        arrayList.add("Primeape");
        arrayList.add("Growlithe");
        arrayList.add("Arcanine");
        arrayList.add("Poliwag");
        arrayList.add("Poliwhirl");
        arrayList.add("Poliwrath");
        arrayList.add("Abra");
        arrayList.add("Kadabra");
        arrayList.add("Alakazam");
        arrayList.add("Machop");
        arrayList.add("Machoke");
        arrayList.add("Machamp");
        arrayList.add("Bellsprout");
        arrayList.add("Weepinbell");
        arrayList.add("Victreebel");
        arrayList.add("Tentacool");
        arrayList.add("Tentacruel");
        arrayList.add("Geodude");
        arrayList.add("Graveler");
        arrayList.add("Golem");
        arrayList.add("Ponyta");
        arrayList.add("Rapidash");
        arrayList.add("Slowpoke");
        arrayList.add("Slowbro");
        arrayList.add("Magnemite");
        arrayList.add("Magneton");
        arrayList.add("Farfetch");
        arrayList.add("Doduo");
        arrayList.add("Dodrio");
        arrayList.add("Seel");
        arrayList.add("Dewgong");
        arrayList.add("Grimer");
        arrayList.add("Muk");
        arrayList.add("Shellder");
        arrayList.add("Cloyster");
        arrayList.add("Gastly");
        arrayList.add("Haunter");
        arrayList.add("Gengar");
        arrayList.add("Onix");
        arrayList.add("Drowzee");
        arrayList.add("Hypno");
        arrayList.add("Krabby");
        arrayList.add("Kingler");
        arrayList.add("Voltorb");
        arrayList.add("Electrode");
        arrayList.add("Exeggcute");
        arrayList.add("Exeggutor");
        arrayList.add("Cubone");
        arrayList.add("Marowak");
        arrayList.add("Hitmonlee");
        arrayList.add("Hitmonchan");
        arrayList.add("Lickitung");
        arrayList.add("Koffing");
        arrayList.add("Weezing");
        arrayList.add("Rhyhorn");
        arrayList.add("Rhydon");
        arrayList.add("Chansey");
        arrayList.add("Tangela");
        arrayList.add("Kangaskhan");
        arrayList.add("Horsea");
        arrayList.add("Seadra");
        arrayList.add("Goldeen");
        arrayList.add("Seaking");
        arrayList.add("Staryu");
        arrayList.add("Starmie");
        arrayList.add("Mr");
        arrayList.add("Scyther");
        arrayList.add("Jynx");
        arrayList.add("Electabuzz");
        arrayList.add("Magmar");
        arrayList.add("Pinsir");
        arrayList.add("Tauros");
        arrayList.add("Magikarp");
        arrayList.add("Gyarados");
        arrayList.add("Lapras");
        arrayList.add("Ditto");
        arrayList.add("Eevee");
        arrayList.add("Vaporeon");
        arrayList.add("Jolteon");
        arrayList.add("Flareon");
        arrayList.add("Porygon");
        arrayList.add("Omanyte");
        arrayList.add("Omastar");
        arrayList.add("Kabuto");
        arrayList.add("Kabutops");
        arrayList.add("Aerodactyl");
        arrayList.add("Snorlax");
        arrayList.add("Articuno");
        arrayList.add("Zapdos");
        arrayList.add("Moltres");
        arrayList.add("Dratini");
        arrayList.add("Dragonair");
        arrayList.add("Dragonite");
        arrayList.add("Mewtwo");
        arrayList.add("Mew");
        arrayList.add("Chikorita");
        arrayList.add("Bayleef");
        arrayList.add("Meganium");
        arrayList.add("Cyndaquil");
        arrayList.add("Quilava");
        arrayList.add("Typhlosion");
        arrayList.add("Totodile");
        arrayList.add("Croconaw");
        arrayList.add("Feraligatr");
        arrayList.add("Sentret");
        arrayList.add("Furret");
        arrayList.add("Hoothoot");
        arrayList.add("Noctowl");
        arrayList.add("Ledyba");
        arrayList.add("Ledian");
        arrayList.add("Spinarak");
        arrayList.add("Ariados");
        arrayList.add("Crobat");
        arrayList.add("Chinchou");
        arrayList.add("Lanturn");
        arrayList.add("Pichu");
        arrayList.add("Cleffa");
        arrayList.add("Igglybuff");
        arrayList.add("Togepi");
        arrayList.add("Togetic");
        arrayList.add("Natu");
        arrayList.add("Xatu");
        arrayList.add("Mareep");
        arrayList.add("Flaaffy");
        arrayList.add("Ampharos");
        arrayList.add("Bellossom");
        arrayList.add("Marill");
        arrayList.add("Azumarill");
        arrayList.add("Sudowoodo");
        arrayList.add("Politoed");
        arrayList.add("Hoppip");
        arrayList.add("Skiploom");
        arrayList.add("Jumpluff");
        arrayList.add("Aipom");
        arrayList.add("Sunkern");
        arrayList.add("Sunflora");
        arrayList.add("Yanma");
        arrayList.add("Wooper");
        arrayList.add("Quagsire");
        arrayList.add("Espeon");
        arrayList.add("Umbreon");
        arrayList.add("Murkrow");
        arrayList.add("Slowking");
        arrayList.add("Misdreavus");
        arrayList.add("Unown");
        arrayList.add("Wobbuffet");
        arrayList.add("Girafarig");
        arrayList.add("Pineco");
        arrayList.add("Forretress");
        arrayList.add("Dunsparce");
        arrayList.add("Gligar");
        arrayList.add("Steelix");
        arrayList.add("Snubbull");
        arrayList.add("Granbull");
        arrayList.add("Qwilfish");
        arrayList.add("Scizor");
        arrayList.add("Shuckle");
        arrayList.add("Heracross");
        arrayList.add("Sneasel");
        arrayList.add("Teddiursa");
        arrayList.add("Ursaring");
        arrayList.add("Slugma");
        arrayList.add("Magcargo");
        arrayList.add("Swinub");
        arrayList.add("Piloswine");
        arrayList.add("Corsola");
        arrayList.add("Remoraid");
        arrayList.add("Octillery");
        arrayList.add("Delibird");
        arrayList.add("Mantine");
        arrayList.add("Skarmory");
        arrayList.add("Houndour");
        arrayList.add("Houndoom");
        arrayList.add("Kingdra");
        arrayList.add("Phanpy");
        arrayList.add("Donphan");
        arrayList.add("Porygon2");
        arrayList.add("Stantler");
        arrayList.add("Smeargle");
        arrayList.add("Tyrogue");
        arrayList.add("Hitmontop");
        arrayList.add("Smoochum");
        arrayList.add("Elekid");
        arrayList.add("Magby");
        arrayList.add("Miltank");
        arrayList.add("Blissey");
        arrayList.add("Raikou");
        arrayList.add("Entei");
        arrayList.add("Suicune");
        arrayList.add("Larvitar");
        arrayList.add("Pupitar");
        arrayList.add("Tyranitar");
        arrayList.add("Lugia");
        arrayList.add("Ho-oh");
        return arrayList;
    }

}
